import { Inter } from 'next/font/google'
import './globals.css'
import "@fontsource/roboto";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hipaste.nonprod.hibank.co.id App',
  description: 'Generated by Hipaste.nonprod.hibank.co.id',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}